ORANGE_MONEY_API_URL: "https://api-s1.orange.cm/"
ORANGE_MONEY_USERNAME: "k6d90YKfBQDmHNRH04Jq14CuGwwa"
ORANGE_MONEY_PASSWORD: "3MS4V3zcDRnfcUIANOZsiAtE8QUa"
ORANGE_MONEY_MSISDN: "655418433"
ORANGE_MONEY_PIN: "8965"
ORANGE_MONEY_AUTH_TOKEN: "WU5PVEVIRUFEMjpAWU5vVGVIRUBEMIBST0RBUEk="

MTN_MOMO_API_URL: "https://sandbox.momodeveloper.mtn.com/"
MTN_MOMO_API_KEY: "your_mtn_momo_api_key"
MTN_MOMO_USER_ID: "your_mtn_momo_user_id"
MTN_MOMO_PRIMARY_KEY: "your_mtn_momo_primary_key"

DEFAULT_EMAIL_FROM: "support@theaxismarket.com"
